import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/pagetwoone">PageTwoOne</Link>
        </li>
        <li>
          <Link to="/">FullwebsiteOne</Link>
        </li>
        <li>
          <Link to="/pageone">PageOne</Link>
        </li>
        <li>
          <Link to="/pagethree">PageThree</Link>
        </li>
        <li>
          <Link to="/pagefourone">PageFourOne</Link>
        </li>
        <li>
          <Link to="/pagefiveone">PageFiveOne</Link>
        </li>
        <li>
          <Link to="/pagesixone">PageSixOne</Link>
        </li>
        <li>
          <Link to="/pageseventwo">PageSevenTwo</Link>
        </li>
        <li>
          <Link to="/pageeight">PageEight</Link>
        </li>
        <li>
          <Link to="/cover">Cover</Link>
        </li>
        <li>
          <Link to="/covertwo">CoverTwo</Link>
        </li>
        <li>
          <Link to="/landingpage">Landingpage</Link>
        </li>
        <li>
          <Link to="/fullwebsite">Fullwebsite</Link>
        </li>
        <li>
          <Link to="/pagetwo">PageTwo</Link>
        </li>
        <li>
          <Link to="/pagethreeone">PageThreeOne</Link>
        </li>
        <li>
          <Link to="/pagefour">PageFour</Link>
        </li>
        <li>
          <Link to="/pagefive">PageFive</Link>
        </li>
        <li>
          <Link to="/pagesix">PageSix</Link>
        </li>
        <li>
          <Link to="/pagesevenone">PageSevenOne</Link>
        </li>
        <li>
          <Link to="/pageeightone">PageEightOne</Link>
        </li>
        <li>
          <Link to="/pageseven">PageSeven</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
